<?php
/**
 * TransferApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Paystack
 *
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: techsupport@paystack.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TransferApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TransferApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for transferBulk
     *
     * Initiate Bulk Transfer.
     *
     */
    public function testTransferBulk()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transferDisableOtp
     *
     * Disable OTP requirement for Transfers.
     *
     */
    public function testTransferDisableOtp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transferDisableOtpFinalize
     *
     * Finalize Disabling of OTP requirement for Transfers.
     *
     */
    public function testTransferDisableOtpFinalize()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transferDownload
     *
     * Export Transfers.
     *
     */
    public function testTransferDownload()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transferEnableOtp
     *
     * Enable OTP requirement for Transfers.
     *
     */
    public function testTransferEnableOtp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transferFetch
     *
     * Fetch Transfer.
     *
     */
    public function testTransferFetch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transferFinalize
     *
     * Finalize Transfer.
     *
     */
    public function testTransferFinalize()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transferInitiate
     *
     * Initiate Transfer.
     *
     */
    public function testTransferInitiate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transferList
     *
     * List Transfers.
     *
     */
    public function testTransferList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transferResendOtp
     *
     * Resend OTP for Transfer.
     *
     */
    public function testTransferResendOtp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transferVerify
     *
     * Verify Transfer.
     *
     */
    public function testTransferVerify()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
