<?php
/**
 * PaymentRequestApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Paystack
 *
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: techsupport@paystack.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PaymentRequestApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PaymentRequestApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for paymentRequestArchive
     *
     * Archive Payment Request.
     *
     */
    public function testPaymentRequestArchive()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for paymentRequestCreate
     *
     * Create Payment Request.
     *
     */
    public function testPaymentRequestCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for paymentRequestFetch
     *
     * Fetch Payment Request.
     *
     */
    public function testPaymentRequestFetch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for paymentRequestFinalize
     *
     * Finalize Payment Request.
     *
     */
    public function testPaymentRequestFinalize()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for paymentRequestList
     *
     * List Payment Request.
     *
     */
    public function testPaymentRequestList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for paymentRequestNotify
     *
     * Send Notification.
     *
     */
    public function testPaymentRequestNotify()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for paymentRequestTotals
     *
     * Payment Request Total.
     *
     */
    public function testPaymentRequestTotals()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for paymentRequestUpdate
     *
     * Update Payment Request.
     *
     */
    public function testPaymentRequestUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for paymentRequestVerify
     *
     * Verify Payment Request.
     *
     */
    public function testPaymentRequestVerify()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
